openapi: 3.0.4
info:
  title: Open Source Licenses
  description: Open Source Licenses is a simple tool for getting information on open source licenses. It returns information on various open source licenses.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/openlicenses:
    get:
      summary: Get Open Source Licenses Information
      description: Open Source Licenses is a simple tool for getting information on open source licenses. It returns information on various open source licenses.
      operationId: openlicenses
      parameters:
      - name: name
        in: query
        schema:
          type: string
        required: true
        description: The name of the open source license to get information about
        example: MIT
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  domain_content: false
                  domain_data: false
                  domain_software: true
                  legacy_ids:
                  - mit-license
                  license: MIT
                  name: MIT License
                  license_url: https://opensource.org/licenses/MIT
                  license_status: active
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
